/*
 * This file has been automatically generated by the jrl-cmakemodules.
 * Please see https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/config.hh.cmake for details.
*/

#ifndef UNITREE_DESCRIPTION_CONFIG_HH
# define UNITREE_DESCRIPTION_CONFIG_HH

// Package version (header).
# define UNITREE_DESCRIPTION_VERSION_UNKNOWN_TAG 0 // Used to mention that the current version is unknown.
# define UNITREE_DESCRIPTION_VERSION "0.0.0"
# define UNITREE_DESCRIPTION_MAJOR_VERSION 0
# define UNITREE_DESCRIPTION_MINOR_VERSION 0
# define UNITREE_DESCRIPTION_PATCH_VERSION 0

#define UNITREE_DESCRIPTION_VERSION_AT_LEAST(major, minor, patch) (UNITREE_DESCRIPTION_MAJOR_VERSION>major || (UNITREE_DESCRIPTION_MAJOR_VERSION>=major && \
                                                             (UNITREE_DESCRIPTION_MINOR_VERSION>minor || (UNITREE_DESCRIPTION_MINOR_VERSION>=minor && \
                                                                                                     UNITREE_DESCRIPTION_PATCH_VERSION>=patch))))

#define UNITREE_DESCRIPTION_VERSION_AT_MOST(major, minor, patch) (UNITREE_DESCRIPTION_MAJOR_VERSION<major || (UNITREE_DESCRIPTION_MAJOR_VERSION<=major && \
                                                            (UNITREE_DESCRIPTION_MINOR_VERSION<minor || (UNITREE_DESCRIPTION_MINOR_VERSION<=minor && \
                                                                                                     UNITREE_DESCRIPTION_PATCH_VERSION<=patch))))

// Handle portable symbol export.
// Defining manually which symbol should be exported is required
// under Windows whether MinGW or MSVC is used.
//
// The headers then have to be able to work in two different modes:
// - dllexport when one is building the library,
// - dllimport for clients using the library.
//
// On Linux, set the visibility accordingly. If C++ symbol visibility
// is handled by the compiler, see: http://gcc.gnu.org/wiki/Visibility
//
// Explicit template instantiation on Windows need to add
// dllexport on the definition and dllimport on the declaration.
// The XXX_EXPLICIT_INSTANTIATION_DECLARATION_DLLAPI macro
// should be set on the declaration while
// the XXX_EXPLICIT_INSTANTIATION_DEFINITION_DLLAPI macro
// should be set on the definition.
# if defined _WIN32 || defined __CYGWIN__
// On Microsoft Windows, use dllimport and dllexport to tag symbols.
#  define UNITREE_DESCRIPTION_DLLIMPORT __declspec(dllimport)
#  define UNITREE_DESCRIPTION_DLLEXPORT __declspec(dllexport)
#  define UNITREE_DESCRIPTION_DLLLOCAL
#  define UNITREE_DESCRIPTION_EXPLICIT_INSTANTIATION_DECLARATION_DLLIMPORT __declspec(dllimport)
#  define UNITREE_DESCRIPTION_EXPLICIT_INSTANTIATION_DECLARATION_DLLEXPORT
#  define UNITREE_DESCRIPTION_EXPLICIT_INSTANTIATION_DEFINITION_DLLIMPORT __declspec(dllimport)
#  define UNITREE_DESCRIPTION_EXPLICIT_INSTANTIATION_DEFINITION_DLLEXPORT __declspec(dllexport)
# else
// On Linux, for GCC >= 4, tag symbols using GCC extension.
#  if __GNUC__ >= 4
#   define UNITREE_DESCRIPTION_DLLIMPORT __attribute__ ((visibility("default")))
#   define UNITREE_DESCRIPTION_DLLEXPORT __attribute__ ((visibility("default")))
#   define UNITREE_DESCRIPTION_DLLLOCAL  __attribute__ ((visibility("hidden")))
#   define UNITREE_DESCRIPTION_EXPLICIT_INSTANTIATION_DECLARATION_DLLIMPORT __attribute__ ((visibility("default")))
#   define UNITREE_DESCRIPTION_EXPLICIT_INSTANTIATION_DECLARATION_DLLEXPORT __attribute__ ((visibility("default")))
#   define UNITREE_DESCRIPTION_EXPLICIT_INSTANTIATION_DEFINITION_DLLIMPORT
#   define UNITREE_DESCRIPTION_EXPLICIT_INSTANTIATION_DEFINITION_DLLEXPORT
#  else
// Otherwise (GCC < 4 or another compiler is used), export everything.
#   define UNITREE_DESCRIPTION_DLLIMPORT
#   define UNITREE_DESCRIPTION_DLLEXPORT
#   define UNITREE_DESCRIPTION_DLLLOCAL
#   define UNITREE_DESCRIPTION_EXPLICIT_INSTANTIATION_DECLARATION_DLLIMPORT
#   define UNITREE_DESCRIPTION_EXPLICIT_INSTANTIATION_DECLARATION_DLLEXPORT
#   define UNITREE_DESCRIPTION_EXPLICIT_INSTANTIATION_DEFINITION_DLLIMPORT
#   define UNITREE_DESCRIPTION_EXPLICIT_INSTANTIATION_DEFINITION_DLLEXPORT
#  endif // __GNUC__ >= 4
# endif // defined _WIN32 || defined __CYGWIN__

# ifdef UNITREE_DESCRIPTION_STATIC
// If one is using the library statically, get rid of
// extra information and use standard explicit template
// instantiation keyword.
#  define UNITREE_DESCRIPTION_DLLAPI
#  define UNITREE_DESCRIPTION_LOCAL
#  define UNITREE_DESCRIPTION_EXPLICIT_INSTANTIATION_DECLARATION extern template
# else
// Depending on whether one is building or using the
// library define DLLAPI to import or export and
// define the right explicit template instantiation keyword.
#  ifdef unitree_description_EXPORTS
#   define UNITREE_DESCRIPTION_DLLAPI UNITREE_DESCRIPTION_DLLEXPORT
#   define UNITREE_DESCRIPTION_EXPLICIT_INSTANTIATION_DECLARATION_DLLAPI UNITREE_DESCRIPTION_EXPLICIT_INSTANTIATION_DECLARATION_DLLEXPORT
#   define UNITREE_DESCRIPTION_EXPLICIT_INSTANTIATION_DEFINITION_DLLAPI UNITREE_DESCRIPTION_EXPLICIT_INSTANTIATION_DEFINITION_DLLEXPORT
#  else
#   define UNITREE_DESCRIPTION_DLLAPI UNITREE_DESCRIPTION_DLLIMPORT
#   define UNITREE_DESCRIPTION_EXPLICIT_INSTANTIATION_DECLARATION_DLLAPI UNITREE_DESCRIPTION_EXPLICIT_INSTANTIATION_DECLARATION_DLLIMPORT
#   define UNITREE_DESCRIPTION_EXPLICIT_INSTANTIATION_DEFINITION_DLLAPI UNITREE_DESCRIPTION_EXPLICIT_INSTANTIATION_DEFINITION_DLLIMPORT
#  endif // UNITREE_DESCRIPTION_EXPORTS
#  define UNITREE_DESCRIPTION_LOCAL UNITREE_DESCRIPTION_DLLLOCAL
# endif // UNITREE_DESCRIPTION_STATIC
#endif //! UNITREE_DESCRIPTION_CONFIG_HH
