controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    state_estimator:
      type: legged_controllers/StateEstimator

state_estimator:
  ros__parameters:
    model:
      base_name: "pelvis"
      six_dof_contact_names: [ "LL_FOOT", "LR_FOOT" ]
    estimation:
      position:
        noise: 1e-2
        frame_id: "mid360_link"

