services:

  lowstate_bridge:
    image: theconstructai/g1_description
    container_name: lowstate_bridge
    privileged: true
    network_mode: host
    restart: always
    entrypoint: /ros_entrypoint.sh
    command: ["/bin/bash", "-lc", "source /ros2_ws/install/setup.bash && source /unitree_ros2/cyclonedds_ws/install/setup.bash && ros2 run g1_description lowstate_jointstate_bridge"]
  robot_state_publisher:
    image: theconstructai/g1_description
    container_name: robot_state_publisher
    privileged: true
    network_mode: host
    restart: always
    entrypoint: /ros_entrypoint.sh
    command: ["/bin/bash", "-lc", "source /ros2_ws/install/setup.bash && ros2 launch g1_description robot_state_publisher.launch.py"]
