<?xml version="1.0"?>
<package format="3">
  <name>ros_sensors_package</name>
  <version>0.1.0</version>
  <description>ROS 2 DDS bridge for Livox lidar and RGBD streams used in this workspace.</description>
  <maintainer email="ag@example.com">ag</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>builtin_interfaces</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
